### ISSUE TITLE
Why is the networking head not included in the optimizer?

### ISSUE THREAD

**Issue by ReamonYim** [duowuyms/NetLLM#14]
Dear Author,

Thank you for providing this excellent codebase. While reviewing the optimization process in vp project `run_plm.py`, I noticed that the **networking head (`pipeline.plm.networking_head`)** is not explicitly added to the optimizer in both the `if not args.freeze_plm` and `else` branches. Here is the relevant snippet:

```python
if not args.freeze_plm:
    optimizer_grouped_parameters = [
        {'params': [p for n, p in pipeline.plm.named_parameters() if not any(nd in n for nd in no_decay)], 
         'weight_decay': args.weight_decay, 'lr': args.lr},
        {'params': [p for n, p in pipeline.plm.named_parameters() if any(nd in n for nd in no_decay)], 
         'weight_decay': 0.0, 'lr': args.lr},
        {'params': pipeline.embed_vp.parameters(), 'weight_decay': args.weight_decay, 'lr': args.lr},
        {'params': pipeline.embed_ln.parameters(), 'weight_decay': args.weight_decay, 'lr': args.lr},
        {'params': pipeline.embed_multimodal.parameters(), 'weight_decay': args.weight_decay, 'lr': args.lr}
    ]
else:
    optimizer_grouped_parameters = [
        {'params': pipeline.embed_vp.parameters(), 'weight_decay': args.weight_decay, 'lr': args.lr},
        {'params': pipeline.embed_ln.parameters(), 'weight_decay': args.weight_decay, 'lr': args.lr},
        {'params': pipeline.embed_multimodal.parameters(), 'weight_decay': args.weight_decay, 'lr': args.lr}
    ]
```

From my understanding:
- The **networking head (`networking_head`)** plays a critical role in the final prediction of future viewport coordinates.
- However, it seems that its parameters are not included in the optimizer configuration, meaning they might not be updated during training.

1. Was this an oversight?  
2. If so, should the networking head parameters (`pipeline.plm.networking_head.parameters()`) be explicitly added to `optimizer_grouped_parameters`?  

Thank you for your time and effort. I look forward to your response and clarification!

Best regards,  
Reamon

![image](https://github.com/user-attachments/assets/7f8822e4-236c-448c-b2ac-5451b0719fb4)

**Comment by batmansdu** [comment]
Apologies for the interruption. I encountered the same issue while reviewing the author's code and noticed you've marked this issue as completed. Could you share whether you've figured out the solution? If so, would you mind sharing your insights? I'd greatly appreciate it.
