### ISSUE TITLE
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by mfdj2002** [duowuyms/NetLLM#2]
python run_plm.py --adapt --grad-accum-steps 32 --plm-type llama --plm-size base --rank 128 --device cuda:0 --lr 0.0001 --warmup-steps 2000 --num-epochs 80 --eval-per-epoch 2

Traceback (most recent call last):
  File "run_plm.py", line 23, in <module>
    from plm_special.models.low_rank import peft_model
  File "/data/workspace/fujingkai/NetLLM/adaptive_bitrate_streaming/plm_special/models/low_rank.py", line 3, in <module>
    from peft import LoraConfig, get_peft_model, TaskType, get_peft_model_state_dict
  File "/data/workspace/fujingkai/.conda/envs/abr_netllm/lib/python3.8/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/data/workspace/fujingkai/.conda/envs/abr_netllm/lib/python3.8/site-packages/peft/auto.py", line 21, in <module>
    from transformers import (
  File "/data/workspace/fujingkai/.conda/envs/abr_netllm/lib/python3.8/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/data/workspace/fujingkai/.conda/envs/abr_netllm/lib/python3.8/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/data/workspace/fujingkai/.conda/envs/abr_netllm/lib/python3.8/site-packages/transformers/utils/__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (/data/workspace/fujingkai/.conda/envs/abr_netllm/lib/python3.8/site-packages/huggingface_hub/__init__.py)

pip show huggingface_hub
Name: huggingface-hub
Version: 0.17.3
...

I installed all dependencies following the readme.

I tried solutions in https://github.com/comfyanonymous/ComfyUI/issues/2055, but none of them worked for me. I also tried using another version of huggingface_hub, but tokenizers 0.14.1 requires huggingface_hub<0.18,>=0.16.4 and transformers 4.34.1 (specified by the requirements you mentioned) requires tokenizers<0.15,>=0.14.

**Comment by ReamonYim** [comment]
a little difference:
python run_plm.py --test --plm-type llama --plm-size base --rank 128 --device cuda:0 --model-dir  data/ft_plms/try_llama2_7b
Traceback (most recent call last):
  File "run_plm.py", line 23, in <module>
    from plm_special.models.low_rank import peft_model
  File "D:\Project\NetLLM\NetLLM\adaptive_bitrate_streaming\plm_special\models\low_rank.py", line 3, in <module>
    from peft import LoraConfig, get_peft_model, TaskType, get_peft_model_state_dict
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\peft\auto.py", line 30, in <module>
    from .config import PeftConfig
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\peft\config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\peft\utils\__init__.py", line 22, in <module>
    from .other import (
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\peft\utils\other.py", line 20, in <module>
    import accelerate
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\accelerate\__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\accelerate\accelerator.py", line 34, in <module>
    from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (D:\Downloads\anaconda3\envs\abr_netllm\lib\site-packages\huggingface_hub\__init__.py)

I installed all dependencies following the readme.

pip show huggingface_hub
Name: huggingface-hub
Version: 0.17.3

I tried the following solutions：
- pip install --upgrade huggingface_hub, but there is a dependency conflict with the tokenizers package,  roll back to version 0.17.3
- pip install --upgrade accelerate, get a openprompt error
- pip install --upgrade openprompt, pip install --upgrade scikit-learn, The split_torch_state_dict_into_shards function is still missing from the huggingface_hub library
...

Everything I tried failed😭

**Comment by duowuyms** [comment]
Hi! Thanks for your messages.

We did not meet this error. Did you run our codes on linux?

FYI, here is the huggingface_hub information on our testbed:
Name: huggingface-hub
Version: 0.17.3
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: xxx
Requires: filelock, fsspec, packaging, pyyaml, requests, tqdm, typing-extensions
Required-by: accelerate, datasets, tokenizers, transformers

**Comment by mfdj2002** [comment]
Hi! Thanks for your response. We eventually solved the problem using the following environment:

$ cat netllm.yaml
name: abr_netllm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.0=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==0.31.0
    - attrs==23.2.0
    - bitsandbytes==0.43.2
    - certifi==2024.7.4
    - click==8.1.7
    - datasets==2.14.7
    - dill==0.3.7
    - filelock==3.15.4
    - fsspec==2023.10.0
    - huggingface-hub==0.21.2
    - idna==3.7
    - jinja2==3.1.2
    - joblib==1.4.2
    - loralib==0.1.2
    - markupsafe==2.1.5
    - mpmath==1.3.0
    - multiprocess==0.70.15
    - munch==4.0.0
    - networkx==3.1
    - nltk==3.8.1
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu12==12.1.105
    - openprompt==1.0.1
    - packaging==24.1
    - pandas==2.0.3
    - peft==0.6.2
    - protobuf==5.27.2
    - psutil==6.0.0
    - pyarrow==17.0.0
    - pyarrow-hotfix==0.6
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2024.7.24
    - requests==2.32.3
    - rouge==1.0.0
    - safetensors==0.4.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - sentencepiece==0.1.96
    - sympy==1.13.1
    - tensorboardx==2.6.2.2
    - threadpoolctl==3.5.0
    - tokenizers==0.14.1
    - torch==2.1.0
    - tqdm==4.66.4
    - transformers==4.34.1
    - triton==2.1.0
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - xxhash==3.4.1
