### ISSUE TITLE
Dataset for generalization of ABR simulation

### ISSUE THREAD

**Issue by EricLabile** [duowuyms/NetLLM#5]
Hello! Thanks for your work. Would you like to share more information about the setting information in ABR simulation? 
For example, could you make the SynthVideo and SynthTrace dataset be open-source? Or could you provide a more detailed instruction on how to prepare our own unseen data in Table 3 and to reproduce Figure 12? Thank you!

**Comment by Alice-yyt** [comment]
Hello! could you share the answers?
