### ISSUE TITLE
Memory Occupancy

### ISSUE THREAD

**Issue by hxhebit** [duowuyms/NetLLM#9]
Thank you for your work. Could you let me know how much memory will be required for running the VP fine-tuning task? It seems that my 3090 might not meet the requirements.

**Comment by duowuyms** [comment]
Hi, hxhebit. 
Fine-tuning llama2-7b on the VP tasks requires ~30GB memory. So you may try fine-tuning on a more powerful gpu or two 3090.

**Comment by hxhebit** [comment]
> Hi, hxhebit. Fine-tuning llama2-7b on the VP tasks requires ~30GB memory. So you may try fine-tuning on a more powerful gpu or two 3090.

Thanks for your reply! Does this project support splitting a single model onto multiple GPUs for fine-tuning? Or do I need to make some modifications to it?

**Comment by hxhebit** [comment]
> > Hi, hxhebit. Fine-tuning llama2-7b on the VP tasks requires ~30GB memory. So you may try fine-tuning on a more powerful gpu or two 3090.
> 
> Thanks for your reply! Does this project support splitting a single model onto multiple GPUs for fine-tuning? Or do I need to make some modifications to it?

It works when I set the --device-out and --device-mid.
